### ISSUE TITLE
Information about the algoritmos is not loading 

### ISSUE THREAD

**Issue by laravivis** [hdspgroup/9836_seismic_project#24]
¿What is the issue?

![image](https://user-images.githubusercontent.com/21224311/183209943-0d410149-6d74-4dcf-9a4e-9f8b4fb338fc.png)
The equations do not appear in the pop-up window.

¿How the issue happens?
I select data, then when I click over "algoritmos", the pop-up window opens but it does not show any information.

¿What do you think could be the issue?
No idea.

**Comment by cvcorreap** [comment]
Same for Mac OS

**Comment by Enmartz** [comment]
Related with #23
